sonar.projectKey=htcmx-web-admin
sonar.projectName=HTCMX web-admin (SvelteKit)
sonar.sources=src
sonar.exclusions=**/node_modules/**,**/build/**,**/.svelte-kit/**,**/static/**
sonar.sourceEncoding=UTF-8
